#!/usr/bin/env node
/**
 * Vendor the Umberleaf brand mark into frontend/ and admin/.
 *
 * The generator is deliberately OUTSIDE every repo, at ~/projects/umberleaf-brand
 * (override with UMBERLEAF_BRAND). This script only COPIES what that generator
 * emitted; it never redraws the mark. Run it after regenerating the brand:
 *
 *   python3 ~/projects/umberleaf-brand/generate_outline.py
 *   node scripts/brand/sync.mjs          # or: pnpm brand:sync
 *   node scripts/brand/sync.mjs --check  # verify only, non-zero on drift
 *
 * Every output keeps the master's own 1024 viewBox rather than rescaling the
 * coordinates. That is the whole point: there is exactly ONE set of path numbers
 * in the system, so a copy cannot silently drift by a rounding error, and `--check`
 * can compare the `d` attribute literally. SVG scales itself at render time.
 *
 * Two masters, chosen per output rather than per size:
 *   master_full.svg      rounded tile, glyph at 0.62 of the tile  → favicon, icon, og tile
 *   master_maskable.svg  square full-bleed tile, glyph pulled in to the ~80%
 *                        safe zone                                → maskable, apple-touch
 *
 * apple-touch uses the maskable variant on purpose: iOS ignores our rounding and
 * applies its own mask, so it needs the solid square AND the inset glyph.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const BRAND = process.env.UMBERLEAF_BRAND ?? join(homedir(), 'projects/umberleaf-brand');
const CHECK = process.argv.includes('--check');
const HEADER = `<!-- GENERATED by scripts/brand/sync.mjs from umberleaf-brand/generate_outline.py — do not edit.
     Umberleaf mark, variant D "Outline". Regenerate: pnpm brand:sync -->`;

/** Pull the stroked-leaf path and the tile radius out of a generated master. */
function readMaster(name) {
  const svg = readFileSync(join(BRAND, 'masters', name), 'utf8');
  const path = svg.match(/<path d="([^"]+)"[^>]*stroke-width="([^"]+)"/);
  const rx = svg.match(/<rect[^>]*rx="([^"]+)"/);
  if (!path || !rx) throw new Error(`could not parse ${name} — did the generator change?`);
  return { d: path[1], strokeWidth: path[2], rx: rx[1] };
}

const full = readMaster('master_full.svg');
const mask = readMaster('master_maskable.svg');

/** A 1024-viewBox tile: the leaf stroked over a rect. `ink` is the tile, `leaf` the stroke. */
const tile = (m, ink, leaf) =>
  `<rect width="1024" height="1024" rx="${m.rx}" fill="${ink}"/>` +
  `<path d="${m.d}" fill="none" stroke="${leaf}" stroke-width="${m.strokeWidth}" ` +
  `stroke-linecap="round" stroke-linejoin="round"/>`;

const doc = (label, body, comment = '') =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" role="img" aria-label="${label}">\n` +
  `  ${HEADER}\n${comment}  ${body}\n</svg>\n`;

const TERRA = '#9E4B28';
const PAPER = '#FFFFFF';
// Admin keeps its own ink tile. That was a deliberate decision, not an accident: admin
// tabs must be distinguishable at a glance from the warm-paper frontend icon. Only the
// GLYPH is being unified here — the tile colour stays admin's.
const ADMIN_INK = '#24211B';
const ADMIN_LEAF = '#FAF7F1';

const outputs = {
  'frontend/public/favicon.svg': doc('Umberleaf', tile(full, TERRA, PAPER)),
  'frontend/public/icon.svg': doc('Umberleaf', tile(full, TERRA, PAPER)),
  'frontend/public/apple-touch-icon.svg': doc(
    'Umberleaf',
    tile(mask, TERRA, PAPER),
    '  <!-- iOS ignores transparency and rounding and applies its own mask: solid square, inset glyph. -->\n',
  ),
  'frontend/public/maskable-icon.svg': doc(
    'Umberleaf',
    tile(mask, TERRA, PAPER),
    '  <!-- Full-bleed; glyph inside the ~80% maskable safe zone so platform masks never clip it. -->\n',
  ),
  'admin/public/favicon.svg': doc('Umberleaf Admin', tile(full, ADMIN_INK, ADMIN_LEAF)),
  // The OG card composes the tile with wordmark text, so it keeps its own canvas and
  // nests the 1024 master rather than rescaling any coordinates.
  'frontend/public/og-image.svg':
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" role="img" aria-label="Umberleaf — a premium writing sanctuary">\n` +
    `  ${HEADER}\n` +
    `  <rect width="1200" height="630" fill="#FAF7F1"/>\n` +
    `  <rect x="0" y="0" width="1200" height="12" fill="${TERRA}"/>\n` +
    `  <svg x="96" y="210" width="168" height="168" viewBox="0 0 1024 1024">${tile(full, TERRA, PAPER)}</svg>\n` +
    `  <text x="300" y="300" font-family="Georgia, 'Times New Roman', serif" font-size="96" font-weight="600" fill="#2b2620">Umberleaf</text>\n` +
    `  <text x="302" y="372" font-family="Georgia, 'Times New Roman', serif" font-size="40" fill="#6b6255">A premium writing sanctuary.</text>\n` +
    `  <text x="302" y="430" font-family="Georgia, 'Times New Roman', serif" font-size="28" fill="#8f887a">Write, publish, and read — in Hindi, Urdu, and beyond.</text>\n` +
    `</svg>\n`,
};

let drift = 0;
for (const [rel, content] of Object.entries(outputs)) {
  if (CHECK) {
    const current = readFileSync(rel, 'utf8');
    if (current !== content) {
      console.error(`DRIFT: ${rel} differs from the generated master`);
      drift += 1;
    }
  } else {
    writeFileSync(rel, content);
    console.log(`wrote ${rel}`);
  }
}
if (CHECK) {
  console.log(
    drift === 0 ? 'brand assets in sync' : `${drift} file(s) drifted — run pnpm brand:sync`,
  );
  process.exit(drift === 0 ? 0 : 1);
}
